import type { ProjectSnapshot } from "@novelforge/domain";

const timestamp = "2026-03-15T00:00:00.000Z";

export const sampleProjectSnapshot: ProjectSnapshot = {
  project: {
    id: "project-ashen-sky",
    title: "Ashen Sky",
    logline: "A failed smuggler has one week to escort a living star-map through a collapsing empire.",
    schemaVersion: 1,
    settings: {
      autosaveIntervalMs: 1500,
      autoAnalyze: true,
      editorFontScale: 1,
    },
    createdAt: timestamp,
    updatedAt: timestamp,
    lastOpenedAt: timestamp,
  },
  chapters: [
    {
      id: "chapter-1",
      projectId: "project-ashen-sky",
      title: "Chapter 1: The Wrong Package",
      summary: "Ava accepts a courier job she does not understand.",
      purpose: "Launch the novel's central threat and lock Ava into the mission.",
      majorEvents: ["Ava takes the job", "The package reacts to Ava"],
      emotionalMovement: "Cynicism to alarm",
      characterFocusIds: ["char-ava"],
      setupPayoffNotes: "The map hums when Ava lies.",
      orderIndex: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "chapter-2",
      projectId: "project-ashen-sky",
      title: "Chapter 2: Border Sparks",
      summary: "The team reaches the border while rival forces close in.",
      purpose: "Escalate risk and formalize the ensemble dynamic.",
      majorEvents: ["Customs inspection", "Rian reveals part of the truth"],
      emotionalMovement: "Control to pressure",
      characterFocusIds: ["char-ava", "char-rian"],
      setupPayoffNotes: "Rian cannot touch iron without pain.",
      orderIndex: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  scenes: [
    {
      id: "scene-1",
      projectId: "project-ashen-sky",
      chapterId: "chapter-1",
      orderIndex: 0,
      title: "Dock Nine Exchange",
      summary: "Ava meets the client and realizes the cargo is alive.",
      purpose: "Inciting incident",
      conflict: "Ava wants a quick payout; the client keeps withholding facts.",
      outcome: "Ava takes the package anyway.",
      povCharacterId: "char-ava",
      location: "Dock Nine",
      timeLabel: "Night",
      involvedCharacterIds: ["char-ava", "char-rian"],
      continuityTags: ["star-map", "debt"],
      dependencySceneIds: [],
      manuscriptText:
        "<p>Ava hated jobs that breathed.</p><p>The crate pulsed once under her hand.</p>",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "scene-2",
      projectId: "project-ashen-sky",
      chapterId: "chapter-1",
      orderIndex: 1,
      title: "The Crate Speaks",
      summary: "The cargo addresses Ava by name once they are alone.",
      purpose: "Show the map has agency.",
      conflict: "Ava wants silence; the map wants trust.",
      outcome: "Ava agrees to protect it until sunrise.",
      povCharacterId: "char-ava",
      location: "Warehouse mezzanine",
      timeLabel: "Late night",
      involvedCharacterIds: ["char-ava"],
      continuityTags: ["star-map"],
      dependencySceneIds: ["scene-1"],
      manuscriptText:
        "<p>The voice came from inside the crate, patient as winter.</p>",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "scene-3",
      projectId: "project-ashen-sky",
      chapterId: "chapter-2",
      orderIndex: 0,
      title: "Checkpoint Lanterns",
      summary: "Ava and Rian bluff their way through a militarized border check.",
      purpose: "Introduce the external chase.",
      conflict: "The inspector recognizes Ava from old smuggling reports.",
      outcome: "They cross, but the inspector sends word ahead.",
      povCharacterId: "char-ava",
      location: "Empire border checkpoint",
      timeLabel: "Dawn",
      involvedCharacterIds: ["char-ava", "char-rian", "char-inspector-vale"],
      continuityTags: ["border", "star-map"],
      dependencySceneIds: ["scene-2"],
      manuscriptText:
        "<p>Lantern glass shook in the wind while Ava counted exits.</p>",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  characters: [
    {
      id: "char-ava",
      projectId: "project-ashen-sky",
      name: "Ava Voss",
      role: "Protagonist",
      personalityTraits: ["defensive", "resourceful", "funny under pressure"],
      motivations: "Clear her family debt and stop running.",
      fears: "Becoming responsible for something she cannot save.",
      worldview: "Systems are built to crush the people who trust them.",
      speakingStyle: "Dry, clipped, reactive.",
      vocabularyTendencies: "Short concrete nouns, sarcastic pivots, maritime slang.",
      speechRhythm: "Fast when cornered, sparse when sincere.",
      emotionalBaseline: "Guarded vigilance.",
      relationships: [
        {
          characterId: "char-rian",
          summary: "Distrusts him but depends on his knowledge.",
        },
      ],
      secrets: "She once betrayed a crew to save her brother.",
      arcDirection: "From self-protective survival to chosen responsibility.",
      contradictions: "Claims she does not care, repeatedly risks herself for strangers.",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "char-rian",
      projectId: "project-ashen-sky",
      name: "Rian Sol",
      role: "Mystic courier",
      personalityTraits: ["formal", "self-sacrificing", "secretive"],
      motivations: "Deliver the living map to the observatory intact.",
      fears: "Failing the people who trusted him with the map.",
      worldview: "Every choice writes a pattern somewhere.",
      speakingStyle: "Measured, precise, image-heavy.",
      vocabularyTendencies: "Celestial metaphors, formal verbs.",
      speechRhythm: "Even and deliberate.",
      emotionalBaseline: "Restrained urgency.",
      relationships: [
        {
          characterId: "char-ava",
          summary: "Needs Ava's instincts, worries about her impulsiveness.",
        },
      ],
      secrets: "He already knows the map chose Ava.",
      arcDirection: "From keeper of secrets to honest collaborator.",
      contradictions: "Advocates truth while strategically hiding crucial facts.",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: "char-inspector-vale",
      projectId: "project-ashen-sky",
      name: "Inspector Vale",
      role: "Pursuer",
      personalityTraits: ["patient", "methodical", "humiliatingly calm"],
      motivations: "Capture Ava and seize anything anomalous crossing the border.",
      fears: "Losing control in public.",
      worldview: "Order is mercy.",
      speakingStyle: "Polite threats.",
      vocabularyTendencies: "Official phrasing, subtle menace.",
      speechRhythm: "Unhurried.",
      emotionalBaseline: "Cold poise.",
      relationships: [],
      secrets: "He is reporting to a faction above the empire's chain of command.",
      arcDirection: "From distant hunter to personal nemesis.",
      contradictions: "Talks about order while serving hidden chaos.",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  suggestions: [],
  projectState: {
    projectId: "project-ashen-sky",
    lastRoute: "/chapters",
    openSceneIds: [],
    selectedIds: [],
    viewFilters: {
      activeChapterId: null,
      searchText: "",
      sceneCharacterId: null,
      sceneContinuityTag: null,
      suggestionStatus: null,
    },
    panelLayout: {
      chaptersInspectorWidth: 360,
      sceneLeftWidth: 320,
      sceneRightWidth: 360,
    },
    autosaveState: {
      isSaving: false,
      lastSavedAt: timestamp,
    },
    analysisQueue: [],
    lastFullScanAt: null,
  },
};
