ALTER TABLE project
ADD COLUMN premise TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN central_conflict TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN thematic_intent TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN ending_direction TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN genre TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN tone TEXT NOT NULL DEFAULT '';

ALTER TABLE project
ADD COLUMN audience_notes TEXT NOT NULL DEFAULT '';
